export enum EnvParams {
  HOST = 'HOST',
  PORT = 'PORT',
  DATE_NAGER_URL = 'DATE_NAGER_URL',
  COUNTRIESNOW_URL = 'COUNTRIESNOW_URL',
  POSTGRES_HOST = 'POSTGRES_HOST',
  POSTGRES_PORT = 'POSTGRES_PORT',
  POSTGRES_USER = 'POSTGRES_USER',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_DB = 'POSTGRES_DB',
}
